version: '3.8'

services:
  mysql:
    image: mysql:8.0
    platform: linux/amd64  
    container_name: abdian-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: abdian_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - abdian-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64   
    container_name: abdian-phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - abdian-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: abdian-project
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    networks:
      - abdian-network

volumes:
  db_data:

networks:
  abdian-network:
    driver: bridge
